name: Continuous Integration with Github Actions

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
          cache: maven

      - name: Build Application JAR
        run: mvn -B package --file pom.xml

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up JDK 18 (again?)
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
          cache: maven

      - name: Update dependency graph (again?)
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      - name: Build Application JAR (again?)
        working-directory: ./rest-with-spring-boot-aula-erudio
        run: mvn clean package

      - name: Update dependency graph (again?)
        working-directory: C:/Users/Rodrigo/Documents/workspace-spring-tool-suite-4-4.17.0.RELEASE
        run: docker compose build

      - name: Push to Docker Hub Container Registry
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-erudio:latest ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-erudio:fool-bar
          docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-erudio:${{ github.run-id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-erudio:latest
